AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

require:
  - rubocop-rake
  - rubocop-on-rbs

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line
Layout/LineLength:
  Max: 120
Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false

Naming/MethodParameterName:
  Exclude:
    - examples/**/*.rb
